version: 2

nodejs-image: &nodejs-image
  docker:
    - image: patrickp78/sls

# -----------------------------------------------------------------------------

jobs:
  build:
    <<: *nodejs-image

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout

      - run:
          name: Setup node_modules as a workspace
          command: |
            mkdir -p node_modules

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            npm install

      - run:
          name: Run tests
          command: npm test

      - persist_to_workspace:
          root: node_modules
          paths:
            - '*'

  deploy-dev:
    <<: *nodejs-image

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout

      # Attach a workspace so that we can access artifacts
      - attach_workspace:
          at: node_modules

      - run:
          name: Deploy to DEV
          command: |
            sls deploy --stage dev

  deploy-qa:
    <<: *nodejs-image

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout

      # Attach a workspace so that we can access artifacts
      - attach_workspace:
          at: node_modules

      - run:
          name: Deploy to QA
          command: |
            sls deploy --stage qa

  deploy-prod:
    <<: *nodejs-image

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout

      # Attach a workspace so that we can access artifacts
      - attach_workspace:
          at: node_modules

      - run:
          name: Deploy to PROD
          command: |
            sls deploy --stage prod

# -----------------------------------------------------------------------------

workflows:
    version: 2

    # commits to random branches
    commit_test:
      jobs:

        - build:
            filters:
              branches:
                ignore: /^master$/


    # merge to master
    build_deploy_dev:
      jobs:

        - build:
            filters:
              branches:
                only: master

        - deploy-dev:
            requires:
              - build

            filters:
              branches:
                only: master


    # tagging the repo x.x.x
    build_deploy_by_tag:

      jobs:

        - build:
            filters:
              tags:
                only: /^[0-9]+\.[0-9]+\.[0-9]+$/
              branches:
                ignore: /.*/

        - deploy-dev:
            requires:
              - build

            filters:
              tags:
                only: /.*/

        - deploy-qa:
            requires:
              - build

            filters:
              tags:
                only: /.*/

        - middle-hold:
            type: approval
            requires:
              - deploy-dev
              - deploy-qa

            filters:
              tags:
                only: /.*/

        - deploy-prod:
            requires:
              - middle-hold

            filters:
              tags:
                only: /.*/
