version: 2

nodejs-image: &nodejs-image
  docker:
    - image: circleci/node:10.16

# -----------------------------------------------------------------------------

jobs:
  build:
    <<: *nodejs-image

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-

      - run:
          name: Run tests
          command: npm test


