version: 2

nodejs-image: &nodejs-image
  docker:
    - image: circleci/node:10.16

# -----------------------------------------------------------------------------

jobs:
  build:
    <<: *nodejs-image

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout

      - run:
          name: Setup node_modules as a workspace
          command: |
            mkdir -p node_modules

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - run:
          name: Run tests
          command: npm test

      - persist_to_workspace:
          root: node_modules
          paths:
            - '*'


  deploy-dev:
    <<: *nodejs-image

    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout

      # Attach a workspace so that we can access artifacts
      - attach_workspace:
          at: node_modules

      - run:
          name: 'yada yada'
          command: |
            ls -l node_modules




# -----------------------------------------------------------------------------

workflows:
    version: 2

    commit_test:
        jobs:
            - build:
                filters:
                    branches:
                        ignore: /^master$/
            - deploy-dev:
                filters:
                    branches:
                        ignore: /^master$/


